### PR TITLE
6.0

### PR DESCRIPTION
**Pull request by pvmerlo**
Merging v6 to master

### CODE REVIEW

**Comment by dmitry-ivanov** [comment]
Surely, this PR would not be merged :)

PS: As for supporting Laravel 6, I will do it soon.

**Comment by pvmerlo** [comment]
I'm adapting it for my project for now while the official support doesn't come out xD wrong pull request though, sorry.

**Comment by dmitry-ivanov** [comment]
No problem 😀 

PS: Hopefully, the `6.0` version of the package would be released this week.

**Comment by pvmerlo** [comment]
Nice! I'm getting some errors on string functions like str_contains, ends_with, replace_first etc...  and some array functions like array_get... so I'm replacing them for Str and Arr methods from Laravel helpers described at https://laravel.com/docs/6.0/helpers.

**Pull request closed without merging**
